version: '3'

services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        ports:
            - '27017:27017'
        volumes:
            - db-data:/data/db

    backend:
        build: ./backend
        container_name: backend
        ports:
            - '5000:5000'
        depends_on:
            - mongodb
        environment:
            MONGODB_URI: mongodb://mongodb:27017/users

    frontend:
        build: ./frontend
        container_name: frontend
        network_mode: host
        ports:
            - '5173:5173'
        depends_on:
            - backend
volumes:
    db-data:
